### ISSUE TITLE
Blocked at step 3 

### ISSUE THREAD

**Issue by challenger087** [Dan-Shields/League-OCR-HUD#1]
Hi bro! i want to thank you first for your awesome work, you did a great job really!
I'm excited to edit my owne HUD but im blocked at step 3, i got my API Key but i don't know how to use it, can you please explaine more? or did a video "how to" from A to Z ?

By the way i found your project on Twitter :)

**Comment by Dan-Shields** [comment]
Hey, I've just released the first executable version which should make it way easier to install now. Check out the updated readme and let me know how you get on :)

**Comment by challenger087** [comment]
Awesome! i'll try and come back to you :)

**Comment by challenger087** [comment]
![image](https://user-images.githubusercontent.com/60705849/113627994-8a880c80-9664-11eb-92f3-883619e038a7.png)

**Comment by Dan-Shields** [comment]
I'd recommend just following the instructions for installing from a release, rather than from source. That way you don't need to worry about node or anything other than the program itself

**Comment by challenger087** [comment]
> I'd recommend just following the instructions for installing from a release, rather than from source. That way you don't need to worry about node or anything other than the program itself

Got it! its necessary to have a billing account ? cause i don't have a credit card

**Comment by challenger087** [comment]
I have already did the example of my HUD :D 
![HUD](https://user-images.githubusercontent.com/60705849/113779818-90e2bb00-972e-11eb-976a-d464498a0414.png)

**Comment by Dan-Shields** [comment]
> Got it! its necessary to have a billing account ? cause i don't have a credit card

Yes, I believe google requires you to set up billing. The first month is free but after that they'll charge you roughly $5/hour when using this program.

**Comment by Dan-Shields** [comment]
Gonna close this now, if you have any more questions feel free to comment still, or contact me on discord: Dan Shields#4476

**Comment by challenger087** [comment]
> Gonna close this now, if you have any more questions feel free to comment still, or contact me on discord: Dan Shields#4476

Ok bro! thx :)
