### ISSUE TITLE
I need a tutorial

### ISSUE THREAD

**Issue by NaVTSLOL** [Dan-Shields/League-OCR-HUD#11]
good directly from Brazil! I wanted to make a request, I want to ask for a tutorial because some translations don't come out the right way and I'm doing something wrong when running the cmd and starting to capture the data in real time, if you could please record your screen doing it so that we can here from Brazil we could understand how to do this installation correctly, thank you in advance for your attention and any help is welcome.

**Comment by Dan-Shields** [comment]
The only available tutorial is currently Jakub's, which from what I can see in his discord, you've already seen.

Heres the link just in case: https://www.youtube.com/watch?v=yIO9Y4U9Plg

EDIT: wrong link
