### ISSUE TITLE
2 pc set up

### ISSUE THREAD

**Issue by shinilee** [Dan-Shields/League-OCR-HUD#4]
I can't figure it out how can I use on my set up I have 2 pc streaming set up.

how can I do this? how can I output the .txt files to my streaming pc

**Comment by Dan-Shields** [comment]
Please don't keep opening multiple issues, that makes it more difficult for me to help you.

Right now the only way I know of to use this program across multiple PCs is have the text files be output to a network drive.

With regards to the score display being too big, your only options are to make your overlay bigger than it, or to turn it off.

If the program isn't outputting left_gold, right_gold, baron_timer, drake_timer, that suggests there's an issue with the NDI and/or your Google API setup. If you can give more info I can give you some help with this.

**Comment by shinilee** [comment]
sorry that I post multi :( and my buddy keep telling me I have to leave the score display open to read date directly from the screen... but yes I turn it off mine. and google api setup and ndi how can I give you more info? what do you want me to give? and thank you again

**Comment by Dan-Shields** [comment]
> my buddy keep telling me I have to leave the score display open to read date directly from the screen

Sorry, you're totally right about this. My program works by reading this data, if you wish to have a separate feed that doesn't have the score display you'll have to run the spectator client twice, maybe on 2 PCs.

> what do you want me to give?

Are you getting any errors/information in the console that might help figure out the issue? Also make sure that you're 100% signed up to the Google Cloud vision api correctly, especially make sure you have billing enabled.

**Comment by shinilee** [comment]
you saying same as my buddy saying but when I run on the program without score display ingame it still read the date. and I didn't get any errors and yes I enabled the billing

**Comment by Dan-Shields** [comment]
The data you're missing (left_gold, right_gold, baron_timer, drake_timer) is what needs the score display, but the rest doesn't which is why you're getting that still. Can you screenshot your console while the program is running please?

**Comment by shinilee** [comment]
![image](https://user-images.githubusercontent.com/82671596/117384329-b6d7b880-aeb0-11eb-8f5e-0e191c806edf.png)

i made 2 keys 1 for at my work 1 for at home

**Comment by Dan-Shields** [comment]
Ah sorry, when I say console, I mean the window that pops up when you run the .exe

**Comment by shinilee** [comment]
no I didn't get any errors I will check tomorrow again and will upload the screen shot

**Comment by shinilee** [comment]
![image](https://user-images.githubusercontent.com/82671596/117385443-2189f380-aeb3-11eb-938a-6cf816a2666d.png)

this guy have no score display on and still working fine

**Comment by shinilee** [comment]
https://youtu.be/P4W0yjZNtvs

here is the video that I record

**Comment by Dan-Shields** [comment]
I can see right in the console it says "Did not find any NDI streams in the given wait time"

What does your config look like, and can you double check it is correct.

**Comment by shinilee** [comment]
![image](https://user-images.githubusercontent.com/82671596/117666223-a2761300-b171-11eb-8a45-2a466a5e0677.png)
good morning
I didn't know there was NID output setting in tools but still not changing anything it does same

**Comment by Dan-Shields** [comment]
NDI feeds are named in the format `<source name> (<pc name>)`, e.g. "Test Source (DAN-PC)"

**Comment by shinilee** [comment]
I changed it but still not working for me
OBS > Tools > NDI Output settings > Check Main Output > Main Output name : Test Source
config.json > ndiFeed : "Test Source (DESKTOP-4M3B2H5)"

**Comment by Dan-Shields** [comment]
Sorry its actually machine name first, then source name. So for you it should be "DESKTOP-4M3B2H5 (Test Source)"

**Comment by shinilee** [comment]
it sure it work. But, still nothing change it only showing gametime, left kill, left towers, right kills, right towers and still working without score display.

**Comment by shinilee** [comment]
the exe file doesn't work anymore so i tried npm start method and I get this error please help
![image](https://user-images.githubusercontent.com/82671596/119244694-fa812200-bb40-11eb-8b1c-656a2adc90ef.png)

**Comment by shinilee** [comment]
I'm done it work now thank you
