### ISSUE TITLE
gold not working....

### ISSUE THREAD

**Issue by shinilee** [Dan-Shields/League-OCR-HUD#5]
maybe it's league? I don't know everything working fine and i just test now when I finished make the overlay and the gold doesn't show everything else work. baron, drake, gametime, kills, towers,...

**Comment by shinilee** [comment]
https://youtu.be/3pEar0P18DQ

here is the video

**Comment by shinilee** [comment]
I just tested at my work and it read gold and drake and baron fine
I have 1 pc and 2 monitor on my work place
Left monitor is sub and it's 1920 x 1080
Right monitor is main and it's 2560 x 1080
and it only work on my Right monitor 
on league of legends video setting have to be bordless or windowed it doesn't work on fullscreen

so I tried to make it work on my sub monitor 1920 x 1080 by change main setting from window and it doesn't work it still reading from my right monitor so I took it off from the pc and leave 1920 x 1080 monitor alone and still not working I restart every each test and I also fresh unzip from the league-hud but still it only reading from my 2560 x 1080

I knew it by when the 2 monitor plug in on pc and I main the 1920 x 1080 and launch the league of legends and make the league of legends to windowed and move the league of legends to 2560 x 1080 monitor and when it get to center it read the gold and baron and drake

my home pc set up is same as work 1 gaming pc to 2 monitor
and main monitor is 1920 x 1080 and sub is 2560 x 1080
and when it work it was working fine but right now it only reading drake and baron time only 

I'm going to test when I get home. I'm going to try hide my taskbar or put it on bottom because I'm using it top 

![League OCR HUD issue](https://user-images.githubusercontent.com/82671596/119364400-da567d80-bc7c-11eb-9580-84475f6d1120.png)

**Comment by shinilee** [comment]
I got this totally wrong 
I though it read from my screen but it reading from obs screen
that is why it didn't read gold text since I apply overlay and overlay block the score display

**Comment by shinilee** [comment]
Finally I think I can close this so what I did just now I open 2 obs
No.1 obs for streaming with overlay on
No2 obs for NDI output to google and overlay off

**Comment by Dan-Shields** [comment]
Ah, I'm glad you figured it out, let me know if you have other issues :)
