### ISSUE TITLE
Support Latest LOL Spectator HUD? 

### ISSUE THREAD

**Issue by XPE-Alex** [Dan-Shields/League-OCR-HUD#6]
Hello, I've been testing your program and I don't think it works/supports the latest update of the LOL Spectator HUD where they've changed the top HUD, by adding drake counters for each team. Screenshot below of the newest spectator HUD.

![NDI XPE-HOST-05 (Display1) 11 April 2022 19-57-13](https://user-images.githubusercontent.com/103481413/162885943-55934aa3-a744-40f7-98b0-15386e13606a.png)

**Comment by Dan-Shields** [comment]
Hey Alex, thanks for bringing this to my attention. I don't currently have the time to update this myself, but if you're able to create a pull request I'd be happy to review.

**Comment by Fill30** [comment]
Fixed in 81f3b3d
